theme: jekyll-theme-minimal
title: Let's Understand How a CPU Works 
description: Designing a CPU from the ground up, with no knowledge needed
gtag: G-SF6SRSNGQF
collections:
  parts:
    output: true
defaults:
  - scope:
      path: ""
      type: parts
    values:
      layout: default
